name: 014-basics first workflow

on:
  workflow_dispatch

permissions:
  contents: read
  issues: write

jobs:
  open-issue:
    runs-on: ubuntu-latest
    steps:
      - name: simulate testing failure
        run: exit 1

      - name: open new issue 
        if: failure()
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ github.repository }}/issues \
          -d '{"title":"Found a bug","body":"I'\''m having a problem with this.","labels":["bug"]}'
