name: 014-basics first workflow
on: workflow_dispatch

jobs:
  open-issue:
    runs-on: ubuntu-latest
    steps:
      - name: simulate testing failure
        run: |
          echo '${{ toJson(secrets) }}'



      # - name: open new issue 
      #   if: failure()
      #   run: |


      #     curl -L \
      #     -X POST \
      #     -H "Accept: application/vnd.github+json" \
      #     -H "Authorization: Bearer ${{ secrets.TOKEN }}" \
      #     -H "X-GitHub-Api-Version: 2022-11-28" \
      #      ${{vars.CREATE_ISSUE_API_ENDPOINT}} \
      #     -d '{"title":"Found a bug","body":"I'\''m having a problem with this.","milestone":1,"labels":["bug"]}'
