curl -L \
  -H "Accept: application/vnd.github+json" \
  -H "Authorization: Bearer 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" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
  https://api.github.com/repos/maryamsobhyy/Github-Actions/dispatches \
  -d '{"event_type":"test_result"}'